language: java
install: mvn clean install
script: mvn liquibase:update -P local
script: mvn test
jdk: oraclejdk8
services:
  - postgresql

before_script:
  - psql -c 'CREATE ROLE "SpringBootUser" LOGIN
               ENCRYPTED PASSWORD 'md513445691374efba1aaee7b0912e63af3'
               SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;' -U postgres

  - psql -c 'CREATE DATABASE "SpringBootRestApi"
                 WITH ENCODING='UTF8'
                      OWNER="SpringBootUser"
                      CONNECTION LIMIT=-1;' -U postgres


