language: java
install: mvn clean install
script: mvn test
jdk: oraclejdk8
services:
  - postgresql

before_install:
  - psql -c "CREATE ROLE SpringBootUser WITH LOGIN PASSWORD 'SpringBootPass';" -U postgres

  - psql -c "CREATE DATABASE SpringBootRestApi WITH ENCODING='UTF8' OWNER=SpringBootUser CONNECTION LIMIT=-1;" -U postgres

  - mvn liquibase:update -P local

addons:
  - postgresql: "9.4"
