language: java
install: mvn clean install
script: mvn test
jdk: oraclejdk8
services:
  - postgresql

before_install:
  - psql -c "CREATE USER SpringBootUser WITH LOGIN PASSWORD 'SpringBootPass' SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;" -U postgres
  - psql -c "CREATE DATABASE assignment754 WITH ENCODING='UTF8' OWNER=SpringBootUser CONNECTION LIMIT=-1;" -U postgres
  - psql -c "SELECT * FROM pg_user;" -U postgres

before_script:
  - mvn liquibase:update -P local

addons:
  - postgresql: "9.4"
