language: java
install: mvn clean install
script: mvn test
jdk: oraclejdk8
services:
  - postgresql

before_install:
  - psql -c "CREATE USER springbootuser WITH LOGIN PASSWORD 'springbootpass' SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;" -U postgres
  - psql -c "CREATE DATABASE assignment754 WITH ENCODING='UTF8' OWNER=springbootuser CONNECTION LIMIT=-1;" -U postgres
  - mvn liquibase:update -P local

addons:
  - postgresql: "9.4"
